-- =========================================================
-- Boby - Setup completo do Supabase
-- ---------------------------------------------------------
-- Como usar:
-- 1. Abra o projeto no Supabase.
-- 2. Vá em SQL Editor.
-- 3. Crie/abra um snippet em branco.
-- 4. Copie TODO este arquivo e cole no editor.
-- 5. Clique em Run.
--
-- Este script pode ser executado mais de uma vez com segurança.
-- Ele cria/atualiza:
-- - categories
-- - tasks
-- - app_errors
-- - índices
-- - RLS
-- - permissões para usuários autenticados
-- =========================================================

create table if not exists public.categories (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null,
  position integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(user_id, name)
);

create table if not exists public.tasks (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  category text,
  title text not null,
  notes text not null default '',
  priority text not null default 'normal',
  series_id uuid,
  original_due_date date,
  carried_at date,
  done boolean not null default false,
  due_date date not null default current_date,
  due_time time,
  completed_at timestamptz,
  position integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Compatibilidade com bancos criados por versões antigas do Boby.
alter table public.tasks add column if not exists category text;
alter table public.tasks add column if not exists notes text not null default '';
alter table public.tasks add column if not exists priority text not null default 'normal';
alter table public.tasks add column if not exists series_id uuid;
alter table public.tasks add column if not exists original_due_date date;
alter table public.tasks add column if not exists carried_at date;
alter table public.tasks add column if not exists due_date date;
alter table public.tasks add column if not exists due_time time;
alter table public.tasks add column if not exists completed_at timestamptz;
alter table public.tasks add column if not exists position integer not null default 0;

update public.tasks
set due_date = current_date
where due_date is null;

alter table public.tasks
alter column due_date set default current_date;

alter table public.tasks
alter column due_date set not null;

alter table public.tasks
drop constraint if exists tasks_priority_check;

alter table public.tasks
add constraint tasks_priority_check
check (priority in ('normal', 'high'));

create unique index if not exists categories_user_name_key
on public.categories(user_id, name);

create index if not exists categories_user_position_idx
on public.categories(user_id, position);

create index if not exists tasks_user_position_idx
on public.tasks(user_id, position);

create index if not exists tasks_user_due_date_idx
on public.tasks(user_id, due_date);

alter table public.categories enable row level security;
alter table public.tasks enable row level security;

drop policy if exists "Users can manage own categories" on public.categories;
drop policy if exists "Users can manage own tasks" on public.tasks;

create policy "Users can manage own categories"
on public.categories for all
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create policy "Users can manage own tasks"
on public.tasks for all
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

grant select, insert, update, delete on public.categories to authenticated;
grant select, insert, update, delete on public.tasks to authenticated;

create table if not exists public.app_errors (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade,
  message text not null,
  stack text not null default '',
  path text not null default '',
  context jsonb not null default '{}'::jsonb,
  user_agent text not null default '',
  created_at timestamptz not null default now()
);

create index if not exists app_errors_user_created_idx
on public.app_errors(user_id, created_at desc);

alter table public.app_errors enable row level security;

drop policy if exists "Users can insert own app errors" on public.app_errors;

create policy "Users can insert own app errors"
on public.app_errors for insert
with check (auth.uid() = user_id);

grant insert on public.app_errors to authenticated;
