/* =========================================================
   SELECTORS
   ---------------------------------------------------------
   Centraliza os elementos do DOM.
   ========================================================= */

export const dom = {
  searchCard: document.querySelector("#searchCard"),
  searchInput: document.querySelector("#searchInput"),
  searchCategoryInput: document.querySelector("#searchCategoryInput"),
  searchCompletedDateInput: document.querySelector("#searchCompletedDateInput"),
  openSearchButton: document.querySelector("#openSearchButton"),
  clearSearchButton: document.querySelector("#clearSearchButton"),

  taskInput: document.querySelector("#taskInput"),
  categoryInput: document.querySelector("#categoryInput"),
  priorityInput: document.querySelector("#priorityInput"),
  dueTimeInput: document.querySelector("#dueTimeInput"),
  dueDateInput: document.querySelector("#dueDateInput"),
  recurrenceEnabledInput: document.querySelector("#recurrenceEnabledInput"),
  recurrenceOptions: document.querySelector("#recurrenceOptions"),
  recurrenceEndDateInput: document.querySelector("#recurrenceEndDateInput"),
  recurrenceStartPreview: document.querySelector("#recurrenceStartPreview"),
  recurrenceSummary: document.querySelector("#recurrenceSummary"),
  recurrenceWeekdayInputs: document.querySelectorAll("[name='recurrenceWeekday']"),
  recurrencePresetButtons: document.querySelectorAll("[data-weekday-preset]"),
  addTaskButton: document.querySelector("#addTaskButton"),
  inputCard: document.querySelector("#inputCard"),
  openTaskInputButton: document.querySelector("#openTaskInputButton"),

  taskList: document.querySelector("#taskList"),
  progressPercent: document.querySelector("#progressPercent"),
  progressCircle: document.querySelector("#progressCircle"),

  settingsButton: document.querySelector("#settingsButton"),
  settingsPanel: document.querySelector("#settingsPanel"),

  profileToggle: document.querySelector("#profileToggle"),
  profileContent: document.querySelector("#profileContent"),
  securityToggle: document.querySelector("#securityToggle"),
  securityContent: document.querySelector("#securityContent"),
  appearanceToggle: document.querySelector("#appearanceToggle"),
  appearanceContent: document.querySelector("#appearanceContent"),
  preferencesToggle: document.querySelector("#preferencesToggle"),
  preferencesContent: document.querySelector("#preferencesContent"),
  suggestionsToggle: document.querySelector("#suggestionsToggle"),
  suggestionsContent: document.querySelector("#suggestionsContent"),
  logoutButton: document.querySelector("#logoutButton"),

  profileAvatar: document.querySelector("#profileAvatar"),
  profilePhotoInput: document.querySelector("#profilePhotoInput"),
  profileForm: document.querySelector("#profileForm"),
  profileNameInput: document.querySelector("#profileNameInput"),
  profileBirthDateInput: document.querySelector("#profileBirthDateInput"),
  profileCityInput: document.querySelector("#profileCityInput"),
  saveProfileButton: document.querySelector("#saveProfileButton"),
  profileCurrentPasswordInput: document.querySelector("#profileCurrentPasswordInput"),
  profilePasswordInput: document.querySelector("#profilePasswordInput"),
  profileConfirmPasswordInput: document.querySelector("#profileConfirmPasswordInput"),
  updatePasswordButton: document.querySelector("#updatePasswordButton"),
  sendRecoveryButton: document.querySelector("#sendRecoveryButton"),
  deleteAccountPasswordInput: document.querySelector("#deleteAccountPasswordInput"),
  deleteAccountConfirmationInput: document.querySelector("#deleteAccountConfirmationInput"),
  deleteAccountButton: document.querySelector("#deleteAccountButton"),
  profileStatus: document.querySelector("#profileStatus"),
  securityStatus: document.querySelector("#securityStatus"),
  exportDataButton: document.querySelector("#exportDataButton"),
  importDataInput: document.querySelector("#importDataInput"),
  restoreSnapshotButton: document.querySelector("#restoreSnapshotButton"),
  dataManagementStatus: document.querySelector("#dataManagementStatus"),
  authPanel: document.querySelector("#authPanel"),
  authForm: document.querySelector("#authForm"),
  authLoginTab: document.querySelector("#authLoginTab"),
  authSignupTab: document.querySelector("#authSignupTab"),
  authTitle: document.querySelector("#authTitle"),
  authDescription: document.querySelector("#authDescription"),
  authNameField: document.querySelector("#authNameField"),
  authNameInput: document.querySelector("#authNameInput"),
  authNameError: document.querySelector("#authNameError"),
  authBirthDateField: document.querySelector("#authBirthDateField"),
  authBirthDateInput: document.querySelector("#authBirthDateInput"),
  authBirthDateError: document.querySelector("#authBirthDateError"),
  authEmailInput: document.querySelector("#authEmailInput"),
  authPasswordInput: document.querySelector("#authPasswordInput"),
  authConfirmPasswordField: document.querySelector("#authConfirmPasswordField"),
  authConfirmPasswordInput: document.querySelector("#authConfirmPasswordInput"),
  authCaptchaField: document.querySelector("#authCaptchaField"),
  authCaptchaQuestion: document.querySelector("#authCaptchaQuestion"),
  authCaptchaInput: document.querySelector("#authCaptchaInput"),
  authCaptchaRefreshButton: document.querySelector("#authCaptchaRefreshButton"),
  authCaptchaError: document.querySelector("#authCaptchaError"),
  authSubmitButton: document.querySelector("#authSubmitButton"),
  authGoogleButton: document.querySelector("#authGoogleButton"),
  authGithubButton: document.querySelector("#authGithubButton"),
  authLinkedinButton: document.querySelector("#authLinkedinButton"),
  authResendButton: document.querySelector("#authResendButton"),
  authPasswordToggle: document.querySelector("#authPasswordToggle"),
  authConfirmPasswordToggle: document.querySelector("#authConfirmPasswordToggle"),
  authEmailError: document.querySelector("#authEmailError"),
  authPasswordError: document.querySelector("#authPasswordError"),
  authConfirmPasswordError: document.querySelector("#authConfirmPasswordError"),
  authOfflineNote: document.querySelector("#authOfflineNote"),
  authStatusText: document.querySelector("#authStatusText"),
  authUserName: document.querySelector("#authUserName"),
  authUserLabel: document.querySelector("#authUserLabel"),

  darkModeToggle: document.querySelector("#darkModeToggle"),
  greenModeToggle: document.querySelector("#greenModeToggle"),
  hideDoneToggle: document.querySelector("#hideDoneToggle"),
  confirmDeleteToggle: document.querySelector("#confirmDeleteToggle"),
  carryIncompleteToggle: document.querySelector("#carryIncompleteToggle"),
  languageSelect: document.querySelector("#languageSelect"),
  enableNotificationsButton: document.querySelector("#enableNotificationsButton"),
  notificationStatus: document.querySelector("#notificationStatus"),


  filterGroup: document.querySelector("#filterGroup"),

  greeting: document.querySelector("#greeting"),
  headlineText: document.querySelector("#headlineText"),
  assistantLine: document.querySelector("#assistantLine"),
  assistantCommandInput: document.querySelector("#assistantCommandInput"),
  runAssistantCommandButton: document.querySelector("#runAssistantCommandButton"),
  assistantCommandStatus: document.querySelector("#assistantCommandStatus"),
  syncStatus: document.querySelector("#syncStatus"),
  syncStatusText: document.querySelector("#syncStatusText"),
  openCalendarButton: document.querySelector("#openCalendarButton"),
  previousWeekButton: document.querySelector("#previousWeekButton"),
  nextWeekButton: document.querySelector("#nextWeekButton"),
  goToTodayButton: document.querySelector("#goToTodayButton"),
  weekRangeLabel: document.querySelector("#weekRangeLabel"),
  weekDays: document.querySelector("#weekDays"),
  dayAgendaViewButton: document.querySelector("#dayAgendaViewButton"),
  weekAgendaViewButton: document.querySelector("#weekAgendaViewButton"),
  monthAgendaViewButton: document.querySelector("#monthAgendaViewButton"),
  homeDayView: document.querySelector("#homeDayView"),
  homeMonthView: document.querySelector("#homeMonthView"),
  homeMonthGrid: document.querySelector("#homeMonthGrid"),
  calendarPanel: document.querySelector("#calendarPanel"),
  calendarGrid: document.querySelector("#calendarGrid"),
  calendarWeekdays: document.querySelector("#calendarWeekdays"),
  yearGrid: document.querySelector("#yearGrid"),
  calendarMonthLabel: document.querySelector("#calendarMonthLabel"),
  calendarPeriodButton: document.querySelector("#calendarPeriodButton"),
  previousCalendarPeriodButton: document.querySelector("#previousCalendarPeriodButton"),
  nextCalendarPeriodButton: document.querySelector("#nextCalendarPeriodButton"),
  calendarMonthViewButton: document.querySelector("#calendarMonthViewButton"),
  calendarYearViewButton: document.querySelector("#calendarYearViewButton"),
  closeCalendarButton: document.querySelector("#closeCalendarButton"),

  openCategorySettingsButton: document.querySelector("#openCategorySettingsButton"),
  categoryPanel: document.querySelector("#categoryPanel"),
  categoryList: document.querySelector("#categoryList"),
  newCategoryInput: document.querySelector("#newCategoryInput"),
  addCategoryButton: document.querySelector("#addCategoryButton"),
  closeCategoryPanelButton: document.querySelector("#closeCategoryPanelButton"),

  confirmDeletePanel: document.querySelector("#confirmDeletePanel"),
  cancelDeleteTaskButton: document.querySelector("#cancelDeleteTaskButton"),
  confirmDeleteTaskButton: document.querySelector("#confirmDeleteTaskButton"),

  taskNotesPanel: document.querySelector("#taskNotesPanel"),
  taskNotesTitle: document.querySelector("#taskNotesTitle"),
  taskNotesEditor: document.querySelector("#taskNotesEditor"),
  closeTaskNotesButton: document.querySelector("#closeTaskNotesButton"),
  notesFontName: document.querySelector("#notesFontName"),
  notesFontSize: document.querySelector("#notesFontSize"),
  notesChecklistButton: document.querySelector("#notesChecklistButton"),
  notesColorToggle: document.querySelector("#notesColorToggle"),
  notesColorPopover: document.querySelector("#notesColorPopover"),
  notesCurrentColor: document.querySelector("#notesCurrentColor"),
  notesTextColor: document.querySelector("#notesTextColor"),
  authResetPasswordButton: document.querySelector("#authResetPasswordButton"),
  authRememberField: document.querySelector("#authRememberField"),
  authRememberInput: document.querySelector("#authRememberInput"),
  taskEditPanel: document.querySelector("#taskEditPanel"),
  taskEditForm: document.querySelector("#taskEditForm"),
  closeTaskEditButton: document.querySelector("#closeTaskEditButton"),
  cancelTaskEditButton: document.querySelector("#cancelTaskEditButton"),
  editTaskTitle: document.querySelector("#editTaskTitle"),
  editTaskCategory: document.querySelector("#editTaskCategory"),
  editTaskDate: document.querySelector("#editTaskDate"),
  editTaskTime: document.querySelector("#editTaskTime"),
  editTaskPriority: document.querySelector("#editTaskPriority"),
  taskSeriesNote: document.querySelector("#taskSeriesNote")
};
