-- Boby v58: monitoramento mínimo e suporte à operação em produção.

create table if not exists public.app_errors (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade,
  message text not null,
  stack text not null default '',
  path text not null default '',
  context jsonb not null default '{}'::jsonb,
  user_agent text not null default '',
  created_at timestamptz not null default now()
);

create index if not exists app_errors_user_created_idx
on public.app_errors(user_id, created_at desc);

alter table public.app_errors enable row level security;

drop policy if exists "Users can insert own app errors" on public.app_errors;
create policy "Users can insert own app errors"
on public.app_errors for insert
with check (auth.uid() = user_id);

grant insert on public.app_errors to authenticated;
